# Generated by Django 2.0.3 on 2018-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_cups_remaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_cups_remaining',
            field=models.IntegerField(null=True),
        ),
    ]
